=== Lucien721/AdInvalidDetected/com.ibm.zrl.idmx.2_3_2/target/classes/com/ibm/zrl/idmx/tests/files/parameter/Credential.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns="http://www.zurich.ibm.com/security/idemix/credential"
	xmlns:idxcs="http://www.zurich.ibm.com/security/idemix/credentialStructure"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.zurich.ibm.com/security/idemix/credential"
	elementFormDefault="qualified">

	<xs:import
		namespace="http://www.zurich.ibm.com/security/idemix/credentialStructure"
		schemaLocation="http://www.zurich.ibm.com/~pbi/idmx_2-3/CredentialStructure.xsd" />

	<xs:element name="Credential">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Name" type="NonEmptyStringType"
					minOccurs="0" />
				<xs:element name="References" type="ReferencesType" />
				<xs:element name="Attributes" type="AttributesType" />
				<xs:element name="Signature" type="SignatureType" />
				<xs:element name="Features" type="FeaturesType" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="ReferencesType">
		<xs:all>
			<xs:element name="CredentialStructure" type="xs:anyURI" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="AttributesType">
		<xs:sequence>
			<xs:element name="Attribute" type="AttributeType"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="AttributeType">
		<xs:sequence>
			<xs:choice>
				<xs:element name="Value" type="idxcs:BigIntegerType" />
				<xs:element name="Commitment" type="CommitmentType" />
			</xs:choice>
			<xs:element name="EnumValue" type="NonEmptyStringType"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="NonEmptyStringType" />
	</xs:complexType>

	<xs:complexType name="CommitmentType">
		<xs:sequence>
			<!-- Commitment -->
			<xs:element name="val" type="idxcs:BigIntegerType" />
			<xs:element name="capS" type="idxcs:BigIntegerType" />
			<xs:element name="n" type="idxcs:BigIntegerType" />
			<xs:element name="Bases" type="BasesType" />

			<!-- CommitmentOpening -->
			<xs:element name="CommitmentOpening" type="CommitmentOpeningType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="BasesType">
		<xs:sequence>
			<xs:element name="Base" type="idxcs:BigIntegerType" />
		</xs:sequence>
		<xs:attribute name="num" type="xs:positiveInteger" />
	</xs:complexType>

	<xs:complexType name="CommitmentOpeningType">
		<xs:sequence>
			<xs:element name="Messages" type="MessagesType" />
			<xs:element name="rand" type="idxcs:BigIntegerType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="MessagesType">
		<xs:sequence>
			<xs:element name="Message" type="idxcs:BigIntegerType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="SignatureType">
		<xs:sequence>
			<xs:element name="capA" type="idxcs:BigIntegerType" />
			<xs:element name="e" type="idxcs:BigIntegerType" />
			<xs:element name="v" type="idxcs:BigIntegerType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="FeaturesType">
		<xs:sequence>
			<xs:element name="Updates" type="UpdatesType" minOccurs="0"
				maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="UpdatesType">
		<xs:all>
			<xs:element name="UpdateLocation" type="xs:anyURI" />
			<xs:element name="capU" type="idxcs:BigIntegerType" />
			<xs:element name="vPrime" type="idxcs:BigIntegerType" />
		</xs:all>
	</xs:complexType>

	<xs:simpleType name="NonEmptyStringType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>



</xs:schema>

=== Lucien721/AdInvalidDetected/com.ibm.zrl.idmx.2_3_2/tests/com/ibm/zrl/idmx/tests/files/credentials/Credential_1a.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Credential xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix Credential.xsd">
  <References>
    <CredentialStructure>http://www.zurich.ibm.com/security/idmx/v2/testIssuer/CredStruct1a.xml</CredentialStructure>
  </References>
  <Attributes>
    <Attribute name="attr1">
      <Value>13256785678</Value>
    </Attribute>
    <Attribute name="attr2">
      <Value>0</Value>
    </Attribute>
    <Attribute name="attr3">
      <Value>0</Value>
    </Attribute>
    <Attribute name="attr4">
      <Value>0</Value>
    </Attribute>
  </Attributes>
  <Signature>
    <A>18110932031993794686989674892235866559154499957898128668676525335647622737399140835860852047307074389009269659839194207935989414494966795031268227562277524542437752664649227643382796529132701409129472527112669516058923041879911962886939103126914635942584080899156532397344148004193689997580493553194608256517</A>
    <e>259344723055062059907025491480697571938277889515152306249728583105665800713306759149981690559193987143012367913206299323899696942213235956742930316040331215474863234775744194396997</e>
    <v>22268413932971662190106124902924343836301603730116887106967540413863968275027353193727224690342065321258172380782215896317446239663436755705998318873192382894132662991903130999782149252201692288268745196341267422918963272080898884614447780774795507865233335600371501771294905879713447341547642498349562377246883640030916289545906904031307931262437019442030822983857398088796246317516494402603285052441562435226450780488910189752875286693675068352528610672728006547056462784033537076463934914223554060940637903556489718828881437600697187388278148256704935155541299439910310040571571828370898072060963605484599866718988</v>
  </Signature>
  <Features/>
</Credential>

=== Lucien721/AdInvalidDetected/com.ibm.zrl.idmx.2_3_2/target/classes/com/ibm/zrl/idmx/tests/files/credentials/Credential_complete.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Credential xmlns="http://www.zurich.ibm.com/security/idemix" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zurich.ibm.com/security/idemix Credential.xsd">
  <References>
    <CredentialStructure>http://www.ch.ch/identityCard/v2012/CredStructComplete.xml</CredentialStructure>
  </References>
  <Attributes>
    <Attribute name="FirstName">
      <Value>-688801371937649959579820756394775575840715893149737780334536265877869334605</Value>
    </Attribute>
    <Attribute name="LastName">
      <Value>-21845598845916938605275525313893548943236279141879078706962526334797938325724</Value>
    </Attribute>
    <Attribute name="PrimeEncoding1">
      <Value>17917</Value>
      <EnumValue>Gender;Male</EnumValue>
      <EnumValue>CivilStatus;Common-lawPartner</EnumValue>
      <EnumValue>OfficialLanguage;German</EnumValue>
    </Attribute>
    <Attribute name="SocialSecurityNumber">
      <Value>13256785678</Value>
    </Attribute>
    <Attribute name="BirthDate">
      <Value>0</Value>
    </Attribute>
    <Attribute name="Diet">
      <Commitment>
        <commitment>130728170692314843831259870115934001142861676867298234143928221466587081868406127980236208925994306104339705488633383845546147313170250880183538343435166718382670656256126908881621049883680221932640568943819517024238563640810617749676670249389841162157652273807435036914542336962055089217118913122577760037749</commitment>
        <S>55571308010516325775772804397563826954721782975616763505244304532021859048628361998511244755298982934173311445275180694709929255436695402519466762101235374067050439165792680699135928691481241721119123430420747731483982917117324401503765800781756424232699268299280828330029077975166989899546930591406881122172</S>
        <n>168175487844170513950388302521371120114716112524620926496765517330054171725495656896584249862184756418406186288108771668180877471912553945908843904913386267160245634470074012553681875910063151598605702234312412541093599574008119895485548398230900036828794014512111305771457797997299447378058032973999969029497</n>
        <Bases num="1">
          <Base>80870292815424433790941931417298047578726961513441461255387927888152586708556077383584542394309035847244193876099317461975268327646558959268579678279368418037856208348437465889178035957582916469595115427849256887464038454943866792273522753762944129276627417751015022285136530790223634801994398172104337693588</Base>
        </Bases>
        <CommitmentOpening>
          <Messages>
            <Message>-27504312941977732075957586170872727553942019300228568380937261894832069870739</Message>
          </Messages>
          <rand>10824780833473166050451740631306648684022492978495497071290498521012867079580574609691479868137906081020820324009048979737512208728955004365467761550257741920864601744787683212697674620662167442567194833613259835942911988516721192351550891132654582193345294654276070937948697749476063666225659823242625424207</rand>
        </CommitmentOpening>
      </Commitment>
    </Attribute>
    <Attribute name="Epoch">
      <Value>3619</Value>
    </Attribute>
    <Attribute name="PrimeEncoding2">
      <Commitment>
        <commitment>35810622694386604279595466831386285060629872688200721070926313307794399474979392381219735124569831224532638132402993456064450010193398269155001940060426773681430522958633354987126278270389992195474218308541204797324257005324253233530412610128495987585708226831448391313122025469683045595642855090269940297835</commitment>
        <S>55571308010516325775772804397563826954721782975616763505244304532021859048628361998511244755298982934173311445275180694709929255436695402519466762101235374067050439165792680699135928691481241721119123430420747731483982917117324401503765800781756424232699268299280828330029077975166989899546930591406881122172</S>
        <n>168175487844170513950388302521371120114716112524620926496765517330054171725495656896584249862184756418406186288108771668180877471912553945908843904913386267160245634470074012553681875910063151598605702234312412541093599574008119895485548398230900036828794014512111305771457797997299447378058032973999969029497</n>
        <Bases num="1">
          <Base>80870292815424433790941931417298047578726961513441461255387927888152586708556077383584542394309035847244193876099317461975268327646558959268579678279368418037856208348437465889178035957582916469595115427849256887464038454943866792273522753762944129276627417751015022285136530790223634801994398172104337693588</Base>
        </Bases>
        <CommitmentOpening>
          <Messages>
            <Message>701054585</Message>
          </Messages>
          <rand>30087409492746020315121413068416065289091410209140472135778266636415781241713546424140020275367373696027428852736349114507795474367325737266135261476527700099956559458795849996787683691442389128991196517354667791132819782991572053330763953983113147611388662079896469331679367060532495337170981136780335583492</rand>
        </CommitmentOpening>
      </Commitment>
      <EnumValue>DriverCategory;M</EnumValue>
      <EnumValue>DriverCategory;B</EnumValue>
      <EnumValue>DriverCategory;C</EnumValue>
      <EnumValue>DriverCategory;D</EnumValue>
      <EnumValue>DriverCategory;B1</EnumValue>
      <EnumValue>DriverCategory;F</EnumValue>
      <EnumValue>DriverCategory;G</EnumValue>
    </Attribute>
  </Attributes>
  <Signature>
    <A>53179253054102746694227688912047478175976485573148559479165149222191480733936272664426621206554779472499103298678603974320079120151005932352073945447781942499904786346606190338288996791574846175519186371520765981120091340385939329558237155926541282876473024186549543847971440525084153758999094917463338637836</A>
    <e>259344723055062059907025491480697571938277889515152306249728583105665800713306759149981690559193987143012367913206299323899696942213235956742929687564975926225189041602639440177871</e>
    <v>18270285081133593537882709163083863432736547670982509619869097268497848860363793092195740805827547472218613122695732190679798269228547831807687840819567921293886948085602265599203945306352562299058888686858624057574465626028746535033772661156314583211554951826667969000180155424368000247168091773539791743395165883719731633285038170946137758459834870891327555731446465710820963766909147968431896339860690353444832148621459667108895522338601762304075421002293590482100386702170361231302316569053501112458761886408064132237878758422506381810773705398813767531238166438769535664903302115656591526820307056170802033842186</v>
  </Signature>
  <Features>
    <Updates>
      <UpdateSpecification>file:/G:/eclipse-workspace/com.ibm.zrl.idmx.2_3_2/tests/com/ibm/zrl/idmx/tests/files/update/Update_81hlb0dimfbf3b27lqqb.xml</UpdateSpecification>
      <capU>37835328910121595639090221364073648164267502652995114198748942915520412616924807238576730690698078242097232893119222393388015052642137162360291756646356239164063734399190110384925172495123379528239224798601426957518844324042949638685410346457288133125755215096116430404730383925857225261469049138568050476204</capU>
      <vPrime>116062890138102766802411975933352311464530148520017001307312392796737936101408738126806055818132388292938682927262284307804610812150730154880521367426052506851994539069628931054016607623211861027112630742750209375320768185740616462153120876980152940208597982664217218339897491211552445699352795216716393651078363028871432473224811387</vPrime>
      <nonce>11532469398607398538008</nonce>
      <context>-596810360451597175840593088383104569515698272461169843343412425743889471929</context>
    </Updates>
  </Features>
</Credential>
